### ISSUE TITLE
Implement Read_Eeprom_Memory?

### ISSUE THREAD

**Issue by DirtyEngineer** [Robopoly/Stand-alone-ISP-Programmer-for-Arduino#1]
Reading through your code for this project I found a commented out case for
//case 'e': read_eeprom_memory()
and
//case 't': eeprom_memory_test()

Did you ever implement this? I've been trying to write code that allows one AVR to read/write to another AVR's Eeprom memory and it would be really helpful if I could see how you did this. Thanks for sharing your code. I have learned a lot from it.

**Comment by patou01** [comment]
Hi,

As far as we know, those features have not be implemented on our side. Good luck with your project! :)

**Comment by DirtyEngineer** [comment]
I got it figured out. Details are at this link
[https://forum.arduino.cc/index.php?topic=462420.0](url)
